import { 
  Trip, 
  Traveler, 
  TripRegistration, 
  RegistrationPayment, 
  Expense, 
  Partner, 
  AuditLog, 
  AgencySettings, 
  UserProfile,
  Product
} from '../types';

export const INITIAL_SETTINGS: AgencySettings = {
  agencyName: 'Raon System — Gestão de Viagens',
  cnpj: '34.821.902/0001-44',
  phone: '(82) 3324-1020',
  whatsapp: '(82) 99824-1020',
  email: 'somosraon@gmail.com',
  address: 'Av. Fernandes Lima, 1420 - Sala 402, Farol',
  city: 'Maceió',
  state: 'AL',
  pixKey: '34.821.902/0001-44',
  pixKeyType: 'CNPJ',
  bankName: 'Banco Inter (077)',
  bankAccount: 'Ag: 0001 / CC: 1829471-2',
  logoUrl: '/images/logo.jpg',
  termsAndConditions: 'Cancelamento com até 7 dias de antecedência tem reembolso de 90%. Vagas transferíveis mediante notificação prévia à Raon System.',
  pendingReservationExpirationHours: 48,
  useSupabase: false,
};

export const INITIAL_USER: UserProfile = {
  id: 'usr_admin_1',
  name: 'Raon admin',
  email: 'somosraon@gmail.com',
  role: 'admin',
};

export const INITIAL_PARTNERS: Partner[] = [
  {
    id: 'part_1',
    name: 'Viação TransBrasil Turismo',
    category: 'Transportadora',
    responsibleName: 'Carlos Eduardo',
    phone: '(82) 3221-9000',
    whatsapp: '82999812233',
    email: 'fretamento@transbrasil.com.br',
    city: 'Maceió',
    state: 'AL',
    address: 'Av. Menino Marcelo, 3500 - Serraria',
    notes: 'Frota de ônibus leito turismo DD com ar, wifi, tomada USB e água mineral.',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'part_2',
    name: 'Pousada Maragogi Sol & Mar',
    category: 'Hotel / Pousada',
    responsibleName: 'Dra. Mariana Costa',
    phone: '(82) 3296-1500',
    whatsapp: '82988114455',
    email: 'reservas@maragogisolemar.com.br',
    city: 'Maragogi',
    state: 'AL',
    address: 'Rodovia AL-101 Norte, Km 125',
    notes: 'Pousada beira-mar com café da manhã reforçado e área de lazer.',
    createdAt: '2026-08-12T11:00:00Z',
  },
  {
    id: 'part_3',
    name: 'Guia Regional Ouro de Minas',
    category: 'Guia de Turismo',
    responsibleName: 'Afonso Queiroz (Cadastur)',
    phone: '(31) 3551-2244',
    whatsapp: '31997654321',
    email: 'afonso.guia@ourodeminas.com.br',
    city: 'Ouro Preto',
    state: 'MG',
    address: 'Praça Tiradentes, 80 - Centro',
    notes: 'Guia credenciado especialista em arte sacra e história do barroco mineiro.',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'part_4',
    name: 'Seguradora Viagem Tranquila SulAmérica',
    category: 'Seguradora',
    responsibleName: 'Luciana Mendes',
    phone: '0800 702 2244',
    whatsapp: '11993332211',
    email: 'coletivo@viagemtranquila.com.br',
    city: 'São Paulo',
    state: 'SP',
    address: 'Av. Paulista, 1000',
    notes: 'Apólice de seguro viagem nacional com cobertura médica de R$ 30.000,00 e extravio de bagagem.',
    createdAt: '2026-08-18T14:00:00Z',
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_1',
    slug: 'maragogi-paraiso-alagoano-2026',
    name: 'Maragogi & Piscinas Naturais Paradisíacas',
    destination: 'Maragogi, Alagoas',
    category: 'Praia',
    description: 'Embarque em uma viagem inesquecível pelo Caribe Brasileiro! Conheça as famosas galés de Maragogi com águas cristalinas, corais exuberantes e passeio exclusivo de catamarã, hospedagem beira-mar e todo o conforto Raon System.',
    imageUrl: '/images/trips/maragogi.jpg',
    departureDate: '2026-11-14',
    returnDate: '2026-11-16',
    departureTime: '06:00',
    departureLocation: 'Posto Tigre - Av. Fernandes Lima, Maceió',
    arrivalLocation: 'Pousada Maragogi Sol & Mar',
    transportType: 'Ônibus Leito Turismo com ar-condicionado e Wi-Fi',
    gatheringTime: '05:30',
    returnTime: '14:00',
    returnArrivalLocation: 'Posto Tigre - Av. Fernandes Lima, Maceió (Chegada prevista: 17:30)',
    capacity: 40,
    responsible: 'Raon admin',
    pricePerPerson: 1450.00,
    status: 'publicada',
    notes: 'Levar protetor solar, óculos escuros e calçado aquático. Taxa de preservação ambiental inclusa.',
    inclusions: [
      'Transporte em Ônibus Leito Turismo com ar-condicionado e Wi-Fi',
      'Hospedagem de 2 noites em pousada beira-mar com café da manhã',
      'Passeio de catamarã às Piscinas Naturais (Galés de Maragogi)',
      'Seguro Viagem Nacional com assistência médica 24h',
      'Guia de Turismo credenciado acompanhante durante todo o roteiro',
      'Kit lanche de bordo exclusivo Raon System',
    ],
    exclusions: [
      'Almoços e jantares à la carte',
      'Mergulho com cilindro e fotos subaquáticas (opcional no local)',
      'Despesas pessoais e frigobar',
    ],
    itinerary: [
      {
        id: 'itin_d1',
        dayNumber: 1,
        date: '2026-11-14',
        title: 'Embarque e Chegada a Maragogi',
        description: 'Saída pela manhã com parada para lanche e recepção beira-mar.',
        activities: [
          {
            id: 'act_1_1',
            time: '06:00',
            title: 'Concentração e Embarque',
            description: 'Apresentação dos passageiros e acomodação de bagagens.',
            location: 'Posto Tigre Maceió',
            order: 1,
          },
          {
            id: 'act_1_2',
            time: '09:00',
            title: 'Chegada e Welcome Drink',
            description: 'Check-in antecipado e boas-vindas na Pousada Sol & Mar.',
            location: 'Pousada Maragogi',
            order: 2,
          },
          {
            id: 'act_1_3',
            time: '14:00',
            title: 'Tarde Livre na Praia de Barra Grande',
            description: 'Caminhada pelo Caminho de Moisés na maré baixa.',
            location: 'Praia de Barra Grande',
            order: 3,
          },
        ],
      },
      {
        id: 'itin_d2',
        dayNumber: 2,
        date: '2026-11-15',
        title: 'Piscinas Naturais & Galés de Maragogi',
        description: 'Dia principal do roteiro com navegação em catamarã.',
        activities: [
          {
            id: 'act_2_1',
            time: '08:30',
            title: 'Embarque no Catamarã',
            description: 'Saída privativa para os recifes de corais na maré baixa de 0.2m.',
            location: 'Píer Central',
            order: 1,
          },
          {
            id: 'act_2_2',
            time: '12:30',
            title: 'Almoço Típico com Frutos do Mar',
            description: 'Parada no Restaurante Pontal do Maragogi.',
            location: 'Restaurante Pontal',
            order: 2,
          },
          {
            id: 'act_2_3',
            time: '19:00',
            title: 'Luau Raon System à Beira da Piscina',
            description: 'Música ambiente e confraternização dos viajantes.',
            location: 'Deck da Pousada',
            order: 3,
          },
        ],
      },
      {
        id: 'itin_d3',
        dayNumber: 3,
        date: '2026-11-16',
        title: 'Praia de Antunes e Retorno',
        description: 'Manhã na praia mais bonita da região e retorno confortável.',
        activities: [
          {
            id: 'act_3_1',
            time: '09:00',
            title: 'Passeio à Praia de Antunes',
            description: 'Visita ao coqueiro inclinado famoso e banho de mar cálido.',
            location: 'Praia de Antunes',
            order: 1,
          },
          {
            id: 'act_3_2',
            time: '14:00',
            title: 'Check-out e Embarque de Retorno',
            description: 'Viagem de volta com chegada prevista para 17:30.',
            location: 'Maceió',
            order: 2,
          },
        ],
      },
    ],
    notices: [
      {
        id: 'not_1',
        tripId: 'trip_1',
        title: 'Horário de Concentração e Embarque',
        message: 'Atenção viajantes: nossa saída será pontualmente às 06:00 no Posto Tigre (Av. Fernandes Lima). Solicitamos chegada com 30 minutos de antecedência (05:30) com documento original com foto em mãos.',
        priority: 'importante',
        publishedAt: '2026-11-10T10:00:00Z',
        isActive: true,
      },
      {
        id: 'not_2',
        tripId: 'trip_1',
        title: 'Recomendações de Bagagem e Piscinas Naturais',
        message: 'Recomendamos calçado aquático (sapatilha de neoprene ou crocs), protetor solar, óculos escuros e toalha de praia. O catamarã fornecerá coletes salva-vidas e kit snorkel.',
        priority: 'informativo',
        publishedAt: '2026-11-11T14:30:00Z',
        isActive: true,
      },
    ],
    checklist: [
      {
        id: 'chk_1',
        tripId: 'trip_1',
        title: 'Ônibus Leito Turismo contratado e revisado',
        category: 'transporte',
        isCompleted: true,
        completedAt: '2026-11-01T10:00:00Z',
      },
      {
        id: 'chk_2',
        tripId: 'trip_1',
        title: 'Pousada Sol & Mar confirmada com relação de quartos',
        category: 'hospedagem',
        isCompleted: true,
        completedAt: '2026-11-03T11:00:00Z',
      },
      {
        id: 'chk_3',
        tripId: 'trip_1',
        title: 'Lista de passageiros cadastrados e conferida',
        category: 'passageiros',
        isCompleted: true,
        completedAt: '2026-11-05T15:00:00Z',
      },
      {
        id: 'chk_4',
        tripId: 'trip_1',
        title: 'Documentos e RGs de todos os viajantes recebidos',
        category: 'documentos',
        isCompleted: true,
        completedAt: '2026-11-06T16:00:00Z',
      },
      {
        id: 'chk_5',
        tripId: 'trip_1',
        title: 'Entregas de brindes e mimos preparadas (Kit de bordo Raon System)',
        category: 'brindes',
        isCompleted: false,
        notes: 'Copos personalizados e lanches a separar',
      },
      {
        id: 'chk_6',
        tripId: 'trip_1',
        title: 'Pagamentos dos fornecedores e parceiros efetuados',
        category: 'financeiro',
        isCompleted: true,
        completedAt: '2026-11-07T09:00:00Z',
      },
      {
        id: 'chk_7',
        tripId: 'trip_1',
        title: 'Roteiro finalizado e distribuído aos guias',
        category: 'roteiro',
        isCompleted: true,
        completedAt: '2026-11-08T12:00:00Z',
      },
      {
        id: 'chk_8',
        tripId: 'trip_1',
        title: 'Apólice coletiva de seguro viagem emitida',
        category: 'financeiro',
        isCompleted: true,
        completedAt: '2026-11-08T16:00:00Z',
      },
    ],
    groups: [
      {
        id: 'grp_1',
        tripId: 'trip_1',
        name: 'Família Albuquerque',
        type: 'familia',
        roomNotes: 'Apartamento Triplo Vista Mar',
        notes: 'Ana Clara + familiares',
        createdAt: '2026-09-02T10:30:00Z',
      },
      {
        id: 'grp_2',
        tripId: 'trip_1',
        name: 'Casal Bruno & Carla',
        type: 'casal',
        roomNotes: 'Suíte Casal Cama King',
        notes: 'Assentos 11 e 12 no ônibus',
        createdAt: '2026-09-02T11:15:00Z',
      },
    ],
    boardingSessions: [
      {
        id: 'sess_1',
        tripId: 'trip_1',
        title: 'Retorno do Catamarã - Entrando no Ônibus',
        transportType: 'Ônibus Leito',
        location: 'Estacionamento do Píer Maragogi',
        scheduledTime: '13:30',
        isActive: true,
        createdAt: '2026-11-15T13:00:00Z',
        records: {
          reg_1: { status: 'embarcou', confirmedAt: '2026-11-15T13:12:00Z', selfChecked: true },
          reg_2: { status: 'embarcou', confirmedAt: '2026-11-15T13:14:00Z', selfChecked: true },
          reg_3: { status: 'aguardando', selfChecked: false },
        },
      },
      {
        id: 'sess_0',
        tripId: 'trip_1',
        title: 'Embarque Inicial - Saída de Maceió',
        transportType: 'Ônibus Leito Turismo',
        location: 'Posto Tigre - Av. Fernandes Lima',
        scheduledTime: '06:00',
        isActive: false,
        createdAt: '2026-11-14T05:30:00Z',
        closedAt: '2026-11-14T06:10:00Z',
        records: {
          reg_1: { status: 'embarcou', confirmedAt: '2026-11-14T05:45:00Z', selfChecked: true },
          reg_2: { status: 'embarcou', confirmedAt: '2026-11-14T05:50:00Z', selfChecked: true },
          reg_3: { status: 'embarcou', confirmedAt: '2026-11-14T05:52:00Z', selfChecked: false },
        },
      },
    ],
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'trip_2',
    slug: 'ouro-preto-tiradentes-barroco-2026',
    name: 'Cidades Históricas: Ouro Preto & Tiradentes',
    destination: 'Ouro Preto e Tiradentes, Minas Gerais',
    category: 'Cultural',
    description: 'Uma imersão encantadora na história do Brasil colonial. Ruas de pedra sabão, casarios seculares, obras-primas de Aleijadinho e a inconfundível culinária mineira em fogão a lenha.',
    imageUrl: '/images/trips/colonial.jpg',
    departureDate: '2026-11-20',
    returnDate: '2026-11-23',
    departureTime: '07:00',
    departureLocation: 'Aeroporto Internacional Zumbi dos Palmares (MCZ) - Saguão Principal',
    arrivalLocation: 'Hotel Solar do Rosário - Ouro Preto, MG',
    transportType: 'Aéreo Comercial + Ônibus Executivo Regional',
    flightNumber: 'Voo GOL G3 1482 (MCZ > CNF) / Retorno G3 1483',
    gatheringTime: '05:00',
    returnTime: '17:30',
    returnArrivalLocation: 'Aeroporto Internacional Zumbi dos Palmares (MCZ)',
    capacity: 35,
    responsible: 'Raon admin',
    pricePerPerson: 1890.00,
    status: 'publicada',
    notes: 'Recomendamos sapatos confortáveis e antiderrapantes para as ladeiras de paralelepípedo.',
    inclusions: [
      'Passagens aéreas ida e volta + transporte privativo executivo em MG',
      'Hospedagem 3 noites com café colonial mineiro',
      'Ingressos para a Igreja São Francisco de Assis e Museu da Inconfidência',
      'Passeio de Maria Fumaça entre Ouro Preto e Mariana',
      'Guia historiador local Cadastur',
      'Seguro viagem completo',
    ],
    exclusions: [
      'Bebidas alcoólicas',
      'Almoços e jantares livres',
      'Compras de artesanato e joias de pedra sabão',
    ],
    itinerary: [
      {
        id: 'itin_op1',
        dayNumber: 1,
        date: '2026-11-20',
        title: 'Chegada e Tour pelo Centro Histórico',
        description: 'Voo, recepção pelo guia Afonso e caminhada cultural.',
        activities: [
          {
            id: 'act_op_1',
            time: '07:00',
            title: 'Embarque Aéreo',
            description: 'Voo até BH e transfer panorâmico até Ouro Preto.',
            location: 'Aeroporto Confins / Ouro Preto',
            order: 1,
          },
          {
            id: 'act_op_2',
            time: '15:00',
            title: 'Praça Tiradentes e Museu da Inconfidência',
            description: 'Visita guiada ao acervo histórico dos inconfidentes.',
            location: 'Praça Tiradentes',
            order: 2,
          },
        ],
      },
    ],
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'trip_3',
    slug: 'chapada-dos-veadeiros-aventura-2026',
    name: 'Expedição Chapada dos Veadeiros & Cachoeiras',
    destination: 'Alto Paraíso de Goiás, Goiás',
    category: 'Aventura',
    description: 'Viva a energia mágica do cerrado brasileiro. Cânions monumentais, cachoeiras de água cristalina, trilhas ecológicas e o pôr do sol inesquecível no Jardim de Maytrea.',
    imageUrl: '/images/trips/aventura.jpg',
    departureDate: '2026-12-04',
    returnDate: '2026-12-08',
    departureTime: '05:30',
    departureLocation: 'Aeroporto / Ponto de Encontro Brasília',
    arrivalLocation: 'Pousada Casa Rosa - Alto Paraíso',
    capacity: 25,
    responsible: 'Patrícia (Equipe Raon System)',
    pricePerPerson: 2150.00,
    status: 'publicada',
    notes: 'Nível moderado de caminhada. Trazer mochila leve, cantil, protetor e repelente.',
    inclusions: [
      'Transfer ida e volta Brasília x Alto Paraíso em van executiva',
      'Hospedagem 4 noites com café da manhã artesanal',
      'Taxas de entrada em todos os atrativos naturais e parques',
      'Condutores de turismo de aventura credenciados ICMBio',
      'Seguro ecoturismo com cobertura para trilhas',
    ],
    exclusions: [
      'Refeições e lanches de trilha não especificados',
      'Gastos individuais',
    ],
    itinerary: [],
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
];

export const INITIAL_TRAVELERS: Traveler[] = [
  {
    id: 'trav_1',
    fullName: 'Ana Clara Albuquerque',
    cpf: '81249210452',
    rg: '3491028 SSP/AL',
    birthDate: '1989-05-14',
    phone: '82996541234',
    email: 'ana.albuquerque@gmail.com',
    city: 'Maceió',
    state: 'AL',
    address: 'Rua Deputado José Lages, 420 - Ponta Verde',
    emergencyContactName: 'Roberto Albuquerque (Marido)',
    emergencyContactPhone: '82991238877',
    notes: 'Vegetariana. Solicita assento na frente do ônibus.',
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'trav_2',
    fullName: 'Bruno Vinícius Menezes',
    cpf: '65432198701',
    rg: '2847192 SSP/AL',
    birthDate: '1993-11-22',
    phone: '82987124433',
    email: 'bruno.menezes@yahoo.com.br',
    city: 'Arapiraca',
    state: 'AL',
    address: 'Rua São Francisco, 110 - Centro',
    emergencyContactName: 'Helena Menezes (Mãe)',
    emergencyContactPhone: '82988771122',
    notes: 'Viajante assíduo da Raon System.',
    createdAt: '2026-09-02T11:15:00Z',
  },
  {
    id: 'trav_3',
    fullName: 'Carla Beatriz Silveira',
    cpf: '32198765410',
    rg: '4192837 SSP/PE',
    birthDate: '1985-02-18',
    phone: '81995432109',
    email: 'carla.silveira@outlook.com',
    city: 'Recife',
    state: 'PE',
    address: 'Av. Boa Viagem, 2100 - Boa Viagem',
    emergencyContactName: 'Juliana Silveira (Irmã)',
    emergencyContactPhone: '81987654321',
    notes: 'Alérgica a frutos do mar.',
    createdAt: '2026-09-03T14:20:00Z',
  },
  {
    id: 'trav_4',
    fullName: 'Diego Fernando Cavalcante',
    cpf: '98712345600',
    rg: '1928374 SSP/AL',
    birthDate: '1978-08-30',
    phone: '82991827364',
    email: 'diego.cavalcante@empresa.com.br',
    city: 'Maceió',
    state: 'AL',
    address: 'Av. Álvaro Otacílio, 1500 - Jatiúca',
    emergencyContactName: 'Renata Cavalcante (Esposa)',
    emergencyContactPhone: '82996541122',
    notes: 'Viaja com a família.',
    createdAt: '2026-09-04T09:45:00Z',
  },
  {
    id: 'trav_5',
    fullName: 'Eduarda Vasconcelos Ribeiro',
    cpf: '55443322199',
    rg: '5829103 SSP/SE',
    birthDate: '1995-07-12',
    phone: '79998765432',
    email: 'duda.vasconcelos@gmail.com',
    city: 'Aracaju',
    state: 'SE',
    address: 'Rua Maruim, 550 - Centro',
    emergencyContactName: 'Felipe Ribeiro (Pai)',
    emergencyContactPhone: '79988112233',
    notes: 'Inscrição feita via link público no Instagram.',
    createdAt: '2026-09-08T16:10:00Z',
  },
];

export const INITIAL_REGISTRATIONS: TripRegistration[] = [
  {
    id: 'reg_1',
    tripId: 'trip_1',
    travelerId: 'trav_1',
    status: 'confirmed',
    financialStatus: 'paid',
    contractedAmount: 1450.00,
    discount: 50.00,
    effectiveDue: 1400.00,
    paymentMethod: 'Pix',
    notes: 'Pagou integral com desconto especial de cliente fiel.',
    registeredAt: '2026-09-02T10:30:00Z',
    approvedAt: '2026-09-02T10:35:00Z',
    boardingStatus: 'embarcou',
    boardingTime: '2026-11-14T05:42:00Z',
    boardingSelfChecked: true,
    seatNumber: '04',
    groupId: 'grp_1',
    roomType: 'Apartamento Triplo Vista Mar',
  },
  {
    id: 'reg_2',
    tripId: 'trip_1',
    travelerId: 'trav_2',
    status: 'confirmed',
    financialStatus: 'partial',
    contractedAmount: 1450.00,
    discount: 0.00,
    effectiveDue: 1450.00,
    paymentMethod: 'Pix',
    notes: 'Deu entrada de R$ 725,00 e restante vence 7 dias antes do embarque.',
    registeredAt: '2026-09-02T11:15:00Z',
    approvedAt: '2026-09-02T11:20:00Z',
    boardingStatus: 'embarcou',
    boardingTime: '2026-11-14T05:51:00Z',
    boardingSelfChecked: false,
    seatNumber: '11',
    groupId: 'grp_2',
    roomType: 'Suíte Casal Cama King',
  },
  {
    id: 'reg_3',
    tripId: 'trip_1',
    travelerId: 'trav_3',
    status: 'confirmed',
    financialStatus: 'unpaid',
    contractedAmount: 1450.00,
    discount: 0.00,
    effectiveDue: 1450.00,
    paymentMethod: 'Boleto',
    notes: 'Reserva confirmada. Aguardando compensação do pagamento.',
    registeredAt: '2026-09-03T14:20:00Z',
    approvedAt: '2026-09-03T15:00:00Z',
    boardingStatus: 'aguardando',
    seatNumber: '12',
    groupId: 'grp_2',
    roomType: 'Suíte Casal Cama King',
  },
  {
    id: 'reg_4',
    tripId: 'trip_1',
    travelerId: 'trav_4',
    status: 'pending',
    financialStatus: 'unpaid',
    contractedAmount: 1450.00,
    discount: 0.00,
    effectiveDue: 1450.00,
    paymentMethod: 'Pix',
    notes: 'Inscrito pelo formulário público. Vaga bloqueada provisoriamente.',
    registeredAt: '2026-09-04T09:45:00Z',
    boardingStatus: 'aguardando',
    seatNumber: '18',
  },
  {
    id: 'reg_5',
    tripId: 'trip_1',
    travelerId: 'trav_5',
    status: 'waitlist',
    financialStatus: 'unpaid',
    contractedAmount: 1450.00,
    discount: 0.00,
    effectiveDue: 1450.00,
    notes: 'Inscrita na lista de espera. Aguarda liberação de vaga.',
    registeredAt: '2026-09-08T16:10:00Z',
    boardingStatus: 'aguardando',
  },
  {
    id: 'reg_6',
    tripId: 'trip_2',
    travelerId: 'trav_1',
    status: 'confirmed',
    financialStatus: 'paid',
    contractedAmount: 1890.00,
    discount: 0.00,
    effectiveDue: 1890.00,
    paymentMethod: 'Cartão de Crédito',
    notes: 'Segunda viagem da mesma viajante (Ana Clara) cadastrada separadamente.',
    registeredAt: '2026-09-06T11:00:00Z',
    approvedAt: '2026-09-06T11:05:00Z',
    boardingStatus: 'aguardando',
    seatNumber: '02A',
  },
];

export const INITIAL_PAYMENTS: RegistrationPayment[] = [
  {
    id: 'pay_1',
    registrationId: 'reg_1',
    tripId: 'trip_1',
    travelerId: 'trav_1',
    amount: 1400.00,
    paymentDate: '2026-09-02',
    dueDate: '2026-09-02',
    paymentMethod: 'Pix',
    notes: 'Comprovante conferido no banco.',
    receiptName: 'comprovante_pix_ana_clara.pdf',
    refunded: false,
    createdAt: '2026-09-02T10:35:00Z',
  },
  {
    id: 'pay_2',
    registrationId: 'reg_2',
    tripId: 'trip_1',
    travelerId: 'trav_2',
    amount: 725.00,
    paymentDate: '2026-09-02',
    dueDate: '2026-11-05',
    paymentMethod: 'Pix',
    notes: 'Entrada de 50%. Segunda parcela acordada para 05/11.',
    receiptName: 'recibo_entrada_bruno.png',
    refunded: false,
    createdAt: '2026-09-02T11:20:00Z',
  },
  {
    id: 'pay_3',
    registrationId: 'reg_6',
    tripId: 'trip_2',
    travelerId: 'trav_1',
    amount: 1890.00,
    paymentDate: '2026-09-06',
    paymentMethod: 'Cartão de Crédito',
    notes: 'Parcelado em 6x na máquina Stone da Raon System.',
    receiptName: 'recibo_stone_ana_clara.pdf',
    refunded: false,
    createdAt: '2026-09-06T11:05:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    tripId: 'trip_1',
    description: 'Fretamento de Ônibus Leito DD Maceió x Maragogi (ida e volta)',
    category: 'Transporte',
    partnerId: 'part_1',
    amount: 3800.00,
    date: '2026-09-01',
    dueDate: '2026-11-10',
    isPaid: true,
    paymentMethod: 'Transferência Bancária',
    notes: 'Contrato nº 2026/088 assinado.',
    receiptName: 'nf_transbrasil_3800.pdf',
    createdAt: '2026-09-01T15:00:00Z',
  },
  {
    id: 'exp_2',
    tripId: 'trip_1',
    description: 'Reserva e bloqueio de 20 apartamentos Pousada Sol & Mar',
    category: 'Hospedagem',
    partnerId: 'part_2',
    amount: 8400.00,
    date: '2026-09-03',
    dueDate: '2026-11-01',
    isPaid: false,
    paymentMethod: 'Pix',
    notes: 'Sinal de 30% a ser quitado em outubro.',
    createdAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'exp_3',
    tripId: 'trip_1',
    description: 'Passeio Privativo de Catamarã para as Galés (40 pessoas)',
    category: 'Passeios',
    amount: 2400.00,
    date: '2026-09-05',
    dueDate: '2026-11-15',
    isPaid: false,
    paymentMethod: 'Dinheiro',
    notes: 'R$ 60 por pessoa já com taxa municipal ambiental.',
    createdAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 'exp_4',
    tripId: 'trip_1',
    description: 'Apólice Coletiva Seguro Viagem Nacional (40 passageiros)',
    category: 'Seguro',
    partnerId: 'part_4',
    amount: 600.00,
    date: '2026-09-02',
    dueDate: '2026-09-05',
    isPaid: true,
    paymentMethod: 'Boleto',
    notes: 'Apólice emitida e enviada aos passageiros.',
    receiptName: 'apolice_sulamerica_maragogi.pdf',
    createdAt: '2026-09-02T16:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_1',
    timestamp: '2026-09-01T10:00:00Z',
    action: 'Criação de Viagem',
    entityType: 'trip',
    entityId: 'trip_1',
    details: 'Viagem "Maragogi & Piscinas Naturais" criada com 40 vagas a R$ 1.450,00.',
    user: 'Raon admin',
  },
  {
    id: 'aud_2',
    timestamp: '2026-09-02T10:35:00Z',
    action: 'Confirmação e Pagamento',
    entityType: 'payment',
    entityId: 'pay_1',
    details: 'Pagamento de R$ 1.400,00 registrado via Pix para Ana Clara Albuquerque.',
    user: 'Raon admin',
  },
  {
    id: 'aud_3',
    timestamp: '2026-09-04T09:45:00Z',
    action: 'Nova Inscrição Pública',
    entityType: 'registration',
    entityId: 'reg_4',
    details: 'Diego Fernando Cavalcante realizou pré-inscrição pelo link público da viagem.',
    user: 'Sistema Web (Público)',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Boné Raon System Oficial (Aba Curva)',
    category: 'Vestuário',
    description: 'Boné premium com tecido leve respirável, proteção UV, ajuste traseiro e bordado exclusivo Raon System. Ideal para passeios sob o sol.',
    price: 49.90,
    stock: 28,
    badge: 'Mais Vendido',
    imageUrl: '/images/products/bone.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod_2',
    name: 'Camisa Térmica UV50+ Dry-Fit Raon System',
    category: 'Vestuário',
    description: 'Camisa manga longa com proteção solar permanente UV50+, tecido tecnológico de secagem rápida e alta flexibilidade para praias e trilhas.',
    price: 79.90,
    stock: 35,
    badge: 'Proteção Solar',
    imageUrl: '/images/products/camisa-uv.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T10:15:00Z',
  },
  {
    id: 'prod_3',
    name: 'Carregador Portátil Power Bank 10.000mAh',
    category: 'Eletrônicos',
    description: 'Bateria externa compacta de alta capacidade com tecnologia Fast Charge, 2 portas USB + Type-C e display digital indicador de carga.',
    price: 119.00,
    stock: 14,
    badge: 'Indispensável',
    imageUrl: '/images/products/power-bank.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T10:30:00Z',
  },
  {
    id: 'prod_4',
    name: 'Fones de Ouvido Bluetooth Sem Fio TWS',
    category: 'Eletrônicos',
    description: 'Fones sem fio ergonômicos com isolamento de ruído, estojo recarregável magnético, microfone embutido e autonomia de até 6 horas contínuas.',
    price: 89.90,
    stock: 20,
    badge: 'Conforto no Ônibus',
    imageUrl: '/images/products/fones-bluetooth.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'prod_5',
    name: 'Fones de Ouvido com Fio e Microfone P2',
    category: 'Eletrônicos',
    description: 'Fone de ouvido intra-auricular com fio reforçado antinó, conector padrão 3.5mm P2 estéreo e botão de controle para chamadas e músicas.',
    price: 29.90,
    stock: 45,
    badge: 'Prático & Leve',
    imageUrl: '/images/products/fones-p2.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T11:15:00Z',
  },
  {
    id: 'prod_6',
    name: 'Baterias / Pilhas Alcalinas AA (Pack 4 un)',
    category: 'Utilidades',
    description: 'Blister com 4 pilhas alcalinas AA de alta durabilidade e tecnologia antivazamento. Essencial para câmeras, brinquedos e lanternas de trilha.',
    price: 22.00,
    stock: 50,
    badge: 'Utilidade Essencial',
    imageUrl: '/images/products/pilhas-aa.jpg',
    availableDuringTrip: true,
    createdAt: '2026-09-01T11:30:00Z',
  },
];
